services:
  mongodb:
    image: mongo:4.4.25
    ports:
      - "8011:27017"
    volumes:
      - ./volumes/mongodb:/data/db
  redis:
    image: redis:7.0.4
    ports:
      - "8012:6379"
networks:
  default:
    name: winds-mobi
